# Generated by Django 5.0.6 on 2024-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadisciplina',
            name='inscritos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
