# Generated by Django 5.0.6 on 2024-06-12 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_ofertadisciplina_inscritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='inscritos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SelecaoTemporaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplinas', models.ManyToManyField(to='inscricao.disciplina')),
                ('turmas', models.ManyToManyField(to='inscricao.turma')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
