# Generated by Django 5.0.6 on 2024-06-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_alter_ofertadisciplina_inscritos_selecaotemporaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecaotemporaria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='selecaotemporaria',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscricao.aluno'),
            preserve_default=False,
        ),
    ]
