# Generated by Django 5.0.6 on 2024-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_remove_selecaotemporaria_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas_cursadas',
            field=models.ManyToManyField(blank=True, to='inscricao.disciplina'),
        ),
    ]
