# Generated by Django 5.0.6 on 2024-06-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_aluno_disciplinas_cursadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
    ]
