# Generated by Django 5.0.6 on 2024-06-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_disciplina_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='disciplinas_cursadas',
        ),
    ]
