# Generated by Django 5.0.6 on 2024-06-18 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0007_remove_aluno_disciplinas_cursadas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('codigo',)},
        ),
        migrations.AlterUniqueTogether(
            name='listaespera',
            unique_together={('aluno', 'disciplina', 'turma')},
        ),
        migrations.AlterUniqueTogether(
            name='ofertadisciplina',
            unique_together={('disciplina',)},
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('numero',)},
        ),
        migrations.AlterUniqueTogether(
            name='selecaotemporaria',
            unique_together={('aluno',)},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('codigo',)},
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('ano', models.IntegerField(default=2024)),
                ('semestre', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricao.aluno')),
                ('turmas', models.ManyToManyField(to='inscricao.turma')),
            ],
            options={
                'unique_together': {('aluno', 'ano')},
            },
        ),
    ]
