# Generated by Django 5.0.6 on 2024-06-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_alter_disciplina_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selecaotemporaria',
            unique_together=set(),
        ),
    ]
